services:
  db:
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      # MYSQL_DATABASE: iso
    volumes:
      - mysql-data:/var/lib/mysql

    ports:
      - 3306:3306

    expose:
      - 3306
      - 33060

volumes:
  mysql-data: