services:
  db:
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    restart: always
    ports:
      - 3306:3306